/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CadastrarProdutoRouteImport } from './routes/cadastrar-produto'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as FlyersRouteImport } from './routes/flyers'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as AdminFlyersRouteImport } from './routes/admin.flyers'
import { Route as AdminSlidesRouteImport } from './routes/admin.slides'
import { Route as EditarProdutoIdRouteImport } from './routes/editar-produto.$id'
import { Route as ProdutoIdRouteImport } from './routes/produto.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrarProdutoRoute = CadastrarProdutoRouteImport.update({
  id: '/cadastrar-produto',
  path: '/cadastrar-produto',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const FlyersRoute = FlyersRouteImport.update({
  id: '/flyers',
  path: '/flyers',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFlyersRoute = AdminFlyersRouteImport.update({
  id: '/flyers',
  path: '/flyers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSlidesRoute = AdminSlidesRouteImport.update({
  id: '/slides',
  path: '/slides',
  getParentRoute: () => AdminRoute,
} as any)
const EditarProdutoIdRoute = EditarProdutoIdRouteImport.update({
  id: '/editar-produto/$id',
  path: '/editar-produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cadastrar-produto': typeof CadastrarProdutoRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/flyers': typeof FlyersRoute
  '/login': typeof LoginRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/admin/flyers': typeof AdminFlyersRoute
  '/admin/slides': typeof AdminSlidesRoute
  '/editar-produto/$id': typeof EditarProdutoIdRoute
  '/produto/$id': typeof ProdutoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cadastrar-produto': typeof CadastrarProdutoRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/flyers': typeof FlyersRoute
  '/login': typeof LoginRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/admin/flyers': typeof AdminFlyersRoute
  '/admin/slides': typeof AdminSlidesRoute
  '/editar-produto/$id': typeof EditarProdutoIdRoute
  '/produto/$id': typeof ProdutoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cadastrar-produto': typeof CadastrarProdutoRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/flyers': typeof FlyersRoute
  '/login': typeof LoginRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/admin/flyers': typeof AdminFlyersRoute
  '/admin/slides': typeof AdminSlidesRoute
  '/editar-produto/$id': typeof EditarProdutoIdRoute
  '/produto/$id': typeof ProdutoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cadastrar-produto'
    | '/cadastro'
    | '/carrinho'
    | '/flyers'
    | '/login'
    | '/redefinir-senha'
    | '/admin/flyers'
    | '/admin/slides'
    | '/editar-produto/$id'
    | '/produto/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cadastrar-produto'
    | '/cadastro'
    | '/carrinho'
    | '/flyers'
    | '/login'
    | '/redefinir-senha'
    | '/admin/flyers'
    | '/admin/slides'
    | '/editar-produto/$id'
    | '/produto/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cadastrar-produto'
    | '/cadastro'
    | '/carrinho'
    | '/flyers'
    | '/login'
    | '/redefinir-senha'
    | '/admin/flyers'
    | '/admin/slides'
    | '/editar-produto/$id'
    | '/produto/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CadastrarProdutoRoute: typeof CadastrarProdutoRoute
  CadastroRoute: typeof CadastroRoute
  CarrinhoRoute: typeof CarrinhoRoute
  FlyersRoute: typeof FlyersRoute
  LoginRoute: typeof LoginRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  EditarProdutoIdRoute: typeof EditarProdutoIdRoute
  ProdutoIdRoute: typeof ProdutoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastrar-produto': {
      id: '/cadastrar-produto'
      path: '/cadastrar-produto'
      fullPath: '/cadastrar-produto'
      preLoaderRoute: typeof CadastrarProdutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flyers': {
      id: '/flyers'
      path: '/flyers'
      fullPath: '/flyers'
      preLoaderRoute: typeof FlyersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/flyers': {
      id: '/admin/flyers'
      path: '/flyers'
      fullPath: '/admin/flyers'
      preLoaderRoute: typeof AdminFlyersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/slides': {
      id: '/admin/slides'
      path: '/slides'
      fullPath: '/admin/slides'
      preLoaderRoute: typeof AdminSlidesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/editar-produto/$id': {
      id: '/editar-produto/$id'
      path: '/editar-produto/$id'
      fullPath: '/editar-produto/$id'
      preLoaderRoute: typeof EditarProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminFlyersRoute: typeof AdminFlyersRoute
  AdminSlidesRoute: typeof AdminSlidesRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFlyersRoute: AdminFlyersRoute,
  AdminSlidesRoute: AdminSlidesRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CadastrarProdutoRoute: CadastrarProdutoRoute,
  CadastroRoute: CadastroRoute,
  CarrinhoRoute: CarrinhoRoute,
  FlyersRoute: FlyersRoute,
  LoginRoute: LoginRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  EditarProdutoIdRoute: EditarProdutoIdRoute,
  ProdutoIdRoute: ProdutoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
